# Generated by Django 5.0.4 on 2026-04-22 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('DESPESA', 'Despesa'), ('RECEITA', 'Receita')], max_length=20)),
                ('status_ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_razao_social', models.CharField(max_length=255)),
                ('fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('cnpj_cpf', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('FORNECEDOR', 'Fornecedor'), ('CLIENTE', 'Cliente'), ('FATURADO', 'Faturado'), ('AMBOS', 'Ambos')], max_length=20)),
                ('status_ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovimentoContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PAGAR', 'Pagar'), ('RECEBER', 'Receber')], max_length=10)),
                ('numero_nota', models.CharField(max_length=50)),
                ('data_emissao', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descricao_produtos', models.TextField(blank=True, null=True)),
                ('classificacoes', models.ManyToManyField(related_name='movimentos', to='financeiro.classificacao')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='financeiro.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelaContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao_unica', models.CharField(max_length=100, unique=True)),
                ('numero_parcela', models.IntegerField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_vencimento', models.DateField()),
                ('situacao', models.CharField(max_length=50)),
                ('movimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.movimentocontas')),
            ],
        ),
    ]
