# Generated by Django 5.0.4 on 2026-04-22 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classificacao',
            options={'verbose_name': 'Classificação', 'verbose_name_plural': 'Classificações'},
        ),
        migrations.AlterModelOptions(
            name='movimentocontas',
            options={'verbose_name': 'Movimento de Conta', 'verbose_name_plural': 'Movimentos de Contas'},
        ),
        migrations.AlterModelOptions(
            name='parcelacontas',
            options={'verbose_name': 'Parcela', 'verbose_name_plural': 'Parcelas'},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
    ]
