# Generated by Django 5.0.4 on 2026-04-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_alter_classificacao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cnpj_cpf',
            field=models.CharField(max_length=20, unique=True, verbose_name='CNPJ / CPF'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='fantasia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome_razao_social',
            field=models.CharField(max_length=255, verbose_name='Nome / Razão Social'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='status_ativo',
            field=models.BooleanField(default=True, verbose_name='Status Ativo'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='tipo',
            field=models.CharField(choices=[('FORNECEDOR', 'Fornecedor'), ('FATURADO', 'Faturado')], max_length=20, verbose_name='Tipo de Pessoa'),
        ),
    ]
