# Generated by Django 5.0.4 on 2026-06-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_pessoa_cnpj_cpf_alter_pessoa_fantasia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentocontas',
            name='status_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
